spring.application.name=gym-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gym_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d32b509bc9b4b0e3ef8e154562c2f1
jwt.expiration=86400000
